"""Trial invites — single-use links that grant a longer trial than the
public default.

Use case: admin wants to comp a prospect, partner, or hand-picked early
user a 30-day full-access trial (vs the public 7-day). Admin enters
email + days, clicks send; recipient gets a branded "you've been
personally invited" email with a unique signup URL. When they sign up
(or first hit /api/auth/me after sign-up) the invite is consumed and
their `trial_ends_at` is set to `now() + trial_days` instead of the
default.

Single-use by design: each invite belongs to one email and can be
accepted exactly once. Resending an invite reuses the same token (so
old links keep working) — only `sent_at` is bumped.

Lifecycle:
    created  → sent          (sent_at set; recipient has the link)
             → accepted      (accepted_at + accepted_user_id set on signup)
             → revoked       (revoked_at set; link rejects with 410)
             → expired       (expires_at < now(); link rejects with 410)
"""

import secrets
import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


def generate_token() -> str:
    """43-char URL-safe random token (~256 bits of entropy). Long enough
    that brute-forcing the space is infeasible and short enough to fit
    comfortably in a URL/QR code."""
    return secrets.token_urlsafe(32)


class TrialInvite(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "trial_invites"

    email: Mapped[str] = mapped_column(String(320), nullable=False, index=True)
    """Lowercase, validated by the admin endpoint before insert."""

    token: Mapped[str] = mapped_column(
        String(64), unique=True, nullable=False, index=True
    )
    """URL-safe random token shown in the invite URL. Generated by
    generate_token() at create-time."""

    trial_days: Mapped[int] = mapped_column(Integer, nullable=False)
    """How many days of Pro trial to grant when this invite is claimed.
    Bounded to 1-180 in the admin endpoint."""

    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    """Optional admin-internal note (not shown to recipient). E.g.
    'Met at Drupa booth, runs a 12-press shop in Manchester'."""

    invited_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    """Which admin sent this invite. Nulled if the admin user is deleted
    so we don't lose the invite history."""

    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    """When the *link* expires (separate from the granted trial duration
    itself). Defaults to 30 days from creation in the admin endpoint —
    if the recipient hasn't clicked through by then we assume they're
    not interested."""

    sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    """Timestamp of the most recent successful send. Null = send failed
    or hasn't been attempted."""

    accepted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    accepted_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    def __repr__(self) -> str:
        return f"<TrialInvite {self.email!r} {self.trial_days}d>"
